# Generated by Django 3.2.15 on 2024-08-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0038_auto_20240821_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость заказа'),
        ),
    ]
