# Generated by Django 3.2.15 on 2024-08-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Заказ принят'), ('processing', 'Заказ собирается'), ('delivering', 'Заказ доставляется'), ('completed', 'Выполнен')], default='accepted', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
