# Generated by Django 3.2.15 on 2024-09-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_remove_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
