version: '3'

services:
  web:
    container_name: star_burger
    build:
      context: ..
      dockerfile: docker_prod/Dockerfile
    restart: always
    env_file:
      - ../.env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - parcel
    command: sh -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn -w 3 -b 0.0.0.0:8000 star_burger.wsgi:application"
    volumes:
      - ../static:/app/static
      - ../media:/app/media

  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    restart: always
    env_file:
      - ../.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  parcel:
    image: node:16-alpine
    working_dir: /code
    command: /bin/sh -c "npm ci --dev && ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url='./'"
    volumes:
      - ..:/code
    env_file:
      - ../.env

volumes:
  db_data:
