# Generated by Django 3.2.15 on 2024-08-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distance_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='distance_km',
            field=models.FloatField(default=0.0),
        ),
    ]
